services:
  db:
    image: mysql:8.0
    container_name: mysql_lm_container
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: fastapi_lm_container
    restart: always
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - FASTAPI_PORT=8001
      - API_KEY=My_Server_API_Key-123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./static:/code/static

volumes:
  mysql_data:
